### ISSUE TITLE
Occasional error opening containers resulting in having to force close game

### ISSUE THREAD

**Issue by AaronAyante** [MSchmoecker/No-Chest-Block#3] opened 2022-12-26 19:41 UTC
I posted this to the OdinQOL page, and they said it was something within MUC causing it. Basically, every now and then, opening a chest will cause a player to get locked in on that chest, unable to close it out. The only solution I've found is to have another player access the chest and take the last item out.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinQOL.Patches.AutoStorePatch.DisallowItem (Container container, ItemDrop+ItemData item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch.TryStoreItem (Container instance, ItemDrop+ItemData& item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch+Container_CheckForChanges_Patch.Postfix (Container instance, ZNetView _m_nview) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
(wrapper dynamic-method) Container.DMD<Container::CheckForChanges>(Container)
MultiUserChest.Patches.InventoryGuiPatch.InventoryGuiUpdatePatch (InventoryGui instance) (at <c1c2835977164751bf3856a33b26f869>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)
![image](https://user-images.githubusercontent.com/50406271/209579105-9ee2dcab-990a-4e5e-8261-6940c23022d0.png)

**Comment by MSchmoecker** [comment] 2022-12-26 20:28
To backref the issue: [OdinsQOL#28](https://github.com/AzumattDev/OdinsQOL/issues/28)

I rather think the root cause is in OdinsQOL, since a similar bug report was already made and it could be reproduced without MUC.

I don't have time to test this myself until Thursday.

**Comment by AaronAyante** [comment] 2022-12-26 23:33
If there's anything I can do to help, please let me know. I'm not much of a programmer, but I've been a stress tester for almost a decade now, so Im versed in the process at least!

**Comment by MSchmoecker** [comment] 2022-12-27 00:10
Thanks but I think there isn't much you can do for now. To sum it up, there is a non-breaking bug in OdinsQOL with the auto store feature and since MUC is calling the method at a different time this causes the inventory to break.

For now you can either remove MUC, disabled the auto store feature or switch to the standalone mod for the auto store, where apperently this bug has already been fixed.

Additionally, I will patch MUC on Thursday so this conflict may not be completely inventory breaking but only throw an accational error. This is not a real fix but should at least lower the symptoms. Since the root cause is in OdinsQOL, which doesn't seem to get an bug fix for this as it will be replaced by the standalone mods,  there is not much I can do here.

**Comment by AaronAyante** [comment] 2022-12-27 02:04
I'm presuming the standalone mod is the AzuAutoStore then? I'll give that a go :) Much appreciated mate!

**Comment by MSchmoecker** [comment] 2022-12-29 17:40
Closing this now as the latest version (0.3.1) shouldn't break the inventory completely.

**Closed by MSchmoecker** 2022-12-29 17:40 UTC
