### ISSUE TITLE
Crash when someone opens a chest

### ISSUE THREAD

**Issue by SuperSid2007** [MSchmoecker/No-Chest-Block#10] opened 2023-12-22 01:35 UTC
Seems like after i placed hoppers down when someone opens one of my chests ive created in crashes my game I dont even need to be near them when they open it

**Comment by MSchmoecker** [comment] 2023-12-25 16:04
Duplicate of MSchmoecker/ValheimHopper#9

**Closed by MSchmoecker** 2023-12-25 16:04 UTC
